site_name: Manual Override
site_description: A groundbreaking exploration of individual consciousness, free will,
  and personal liberation from unconscious programming.
site_author: Rez Khan
site_url: https://universalbookcompiler.com/10_Manual_Override/
site_dir: ../site_build
docs_dir: docs
nav:
- index.md
- Manual Override: manual-override.md
- 'Part 1: The Evidence':
  - part-1-the-evidence.md
  - chapter-1-the-four-stages-of-manual-override-development.md
  - chapter-2-the-automation-evidence.md
  - chapter-3-the-automation-evidence.md
  - chapter-4-the-consciousness-anomalies.md
  - chapter-5-the-cosmic-rhythm-of-consciousness.md
  - chapter-6-foundational-practices-reality-breaking-technologies.md
  - foundational-practices-reality-breaking-technologies.md
  - chapter-7-sarahs-journey-the-first-glitch.md
  - part-2-the-personal-game-awareness-vs-programming.md
- 'Part 3: How Consciousness Actually Works':
  - part-3-how-consciousness-actually-works.md
  - chapter-8-the-observer-from-witness-to-relationship.md
  - chapter-9-the-malleable-mind.md
  - chapter-10-the-perseus-protocol-advanced-consciousness-navigation.md
  - chapter-11-the-body-as-a-process.md
  - chapter-12-the-energetics-of-agency.md
  - chapter-13-the-manifestation-trap.md
  - chapter-14-how-consciousness-influences-reality.md
  - chapter-15-the-path-of-most-votes.md
  - chapter-16-the-presence-paradox.md
  - chapter-17-sarahs-journey-the-quantum-moment.md
  - chapter-18-daily-life-integration-living-manual-override.md
  - chapter-19-common-pitfalls-and-how-to-avoid-them.md
  - chapter-20-building-sustainable-practice-routines.md
- 'Part 4: Application':
  - part-4-application.md
  - chapter-21-the-anatomy-of-a-choice-point.md
  - chapter-22-the-art-of-conscious-resistance.md
  - chapter-23-sarah-interlude-the-mirror-shield.md
  - chapter-24-breaking-free-escaping-reality-programming-loops.md
  - chapter-25-the-paradox-of-surrender.md
  - chapter-26-sarahs-journey-the-glitch-in-the-matrix.md
- 'Part 5: Integration':
  - part-5-integration.md
  - chapter-27-from-the-meditation-cushion-to-the-real-world.md
  - chapter-28-integration-and-navigation-operating-from-multiple-planes.md
  - chapter-29-the-brain-as-receiver-reconciling-consciousness-and-neuroscience.md
  - chapter-30-a-unique-synthesis.md
  - chapter-31-the-game-paradox-why-this-isnt-a-trap.md
  - chapter-32-glitches-in-the-simulation.md
  - chapter-33-conclusion-the-case-closed.md
  - chapter-34-workplace-consciousness.md
  - glossary-of-key-terms.md
  - appendix-a-a-speculative-metaphysical-model.md
- Downloads: downloads/index.md
theme:
  name: material
  palette:
  - scheme: default
    primary: deep purple
    accent: purple
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: deep purple
    accent: purple
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - navigation.footer
  - search.highlight
  - search.share
  - content.code.copy
  - content.action.edit
  - content.action.view
  - content.tabs.link
  font:
    text: Inter
    code: Fira Code
plugins:
- search
- pdf-export:
    verbose: true
    media_type: print
    enabled_if_env: ENABLE_PDF_EXPORT
    combined: true
    combined_output_path: Manual_Override.pdf
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.details
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- admonition
- codehilite
- toc
- tables
- footnotes
- attr_list
- md_in_html
extra_css:
- stylesheets/custom.css
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/DoctorKhan/Universal-Book-Compiler
copyright: Copyright &copy; 2025 Rez Khan
